### ISSUE TITLE
Example for `automatically create a user install` and OpenSSH unlikely to work

### ISSUE THREAD

**Issue by nyetsche** [kha7iq/kc-ssh-pam#2]
Thanks for this very useful PAM module.

This isn't strictly an issue with your code, but something you may want to note in the README for others. The `libpam-script` & `useradd` method to create users from PAM and _SSHD_ is unlikely to work. OpenSSH will set the password to a dummy (which may show up as empty thanks to special characters) value if it cannot confirm the username exists through `getpwnam`.

See https://superuser.com/questions/900417/pam-exec-so-doesnt-write-password-to-script-when-expose-authtok-is-enabled although the answer points to code from a few years ago. I believe more recent OpenSSH software does the "user exists" check in `getpwnamallow`, at https://github.com/openssh/openssh-portable/blob/master/auth.c#L488 which isn't something that can be disabled.

**Comment by kha7iq** [comment]
Hello, 
As far as i tested it does work, there is a caveat that if the user is not created before hand on first try it will fail to login but try again and it works fine because at that point the script creates the user.
The libpam script i mentioned is just for convenience, the main goal was to authenticate the users.
